repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-check
        name: cargo check
        entry: cargo check --workspace --all-targets --features source-build
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-test
        name: cargo test
        entry: cargo test --workspace --features source-build
        language: system
        types: [rust]
        pass_filenames: false
